/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_onzhou_opengles_color_NativeColorRenderer */
#include <android/log.h>
#include "string.h"
#ifndef COM_ONZHOU_OPENGLES_COLOR_NATIVECOLORRENDERER
#define COM_ONZHOU_OPENGLES_COLOR_NATIVECOLORRENDERER
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL drawColor(JNIEnv *, jobject, jobject, jint);

JNIEXPORT void JNICALL drawBitmap(JNIEnv *, jobject, jobject, jobject);

#define LOGTAG "image_native"
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, LOGTAG, __VA_ARGS__)
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO, LOGTAG, __VA_ARGS__)
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR, LOGTAG, __VA_ARGS__)

#ifdef __cplusplus
}
#endif
#endif
